FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
COPY Blazor1.csproj .
RUN dotnet restore "Blazor1.csproj"
COPY . .
RUN dotnet build "Blazor1.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "Blazor1.csproj" -c Debug -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Blazor1.dll"]
